server:
  port: 8884
  servlet:
    context-path: /client
security:
  oauth2:
    client:
      clientId: xxx
      clientSecret: xxxx
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: header
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
spring:
  thymeleaf:
    cache: false
